services:
  nats:
    image: nats:2-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_node
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    command: 
      - "--js"                         # Enable JetStream
      - "--server_name=${DC_NATS_SERVER_NAME:-nats}"  # Server name
      - "--http_port=8222"            # Monitor port
      - "--store_dir=/data"           # Store directory for JetStream
    ports:
      - "${DC_NATS_SERVER_PORT:-4222}:4222"      # Client connections
      - "${DC_NATS_MONITOR_PORT:-8222}:8222"      # HTTP monitor port
      - "${DC_NATS_CLUSTER_PORT:-6222}:6222"      # Route port for clustering
    volumes:
      - ./data/nats:/data  # Persist JetStream data
      - ./configs/nats:/etc/nats
    healthcheck:
      test: ["CMD", "sh", "-c", "wget http://localhost:8222/healthz -q -O - | xargs | grep ok || exit 1"]
      timeout: 5s
      interval: 10s
      retries: 3